# Projeto prático FT045B II - Preparação do Dataset
## Autor: Bruno Ricardo Corrêa

Os dados obtidos no estudo NHANES (2021-2023) estão separados em diferentes datasets, para que seja possível utilizar para o treinamento de modelos de Aprendizado de Máquina, é necessário fazer uma união dos mesmos.

# CORRIGIR NOMES E EXPLICAÇÕES DAS VARIÁVEIS

---

### demographic_df (DEMO_L.xpt)
Contém informações demográficas sobre os entrevistados.

* `SEQN`: Número de sequência do entrevistado (Identificador)
* `SDDSRVYR`: Ano da pesquisa
* `RIDSTATR`: Status da entrevista e exame
* `RIAGENDR`: Gênero
* `RIDAGEYR`: Idade em anos na triagem
* `RIDAGEMN`: Idade em meses na triagem
* `RIDRETH1`: Raça/Origem Hispânica
* `RIDRETH3`: Raça/Origem Hispânica, incluindo Outros Hispânicos
* `RIDEXMON`: Mês da entrevista e exame
* `RIDEXAGM`: Idade em meses no exame
* `DMQMILIZ`: Serviço militar
* `DMDBORN4`: País de nascimento
* `DMDYRUSR`: Anos nos EUA
* `DMDEDUC2`: Nível de educação - Adultos 20+
* `DMDMARTZ`: Estado civil
* `RIDEXPRG`: Status de gravidez no exame
* `DMDHHSIZ`: Tamanho do agregado familiar
* `DMDHRGND`: Gênero do chefe do agregado familiar
* `DMDHRAGZ`: Idade do chefe do agregado familiar
* `DMDHREDZ`: Educação do chefe do agregado familiar
* `DMDHRMAZ`: Estado civil do chefe do agregado familiar
* `DMDHSEDZ`: Educação do chefe do agregado familiar
* `WTINT2YR`: Peso da entrevista
* `WTMEC2YR`: Peso do exame
* `SDMVSTRA`: Pseudo-estrato de variância mascarado
* `SDMVPSU`: Pseudo-PSU de variância mascarada
* `INDFMPIR`: Renda familiar anual (PIR)

---

### bpxo_df (BPXO_L.xpt)
Contém dados de pressão arterial e oximetria.

* `SEQN`: Número de sequência do entrevistado (Identificador)
* `BPAOARM`: Braço usado para pressão arterial e oximetria
* `BPAOCSZ`: Tamanho do manguito usado para pressão arterial
* `BPXOSY1`: Pressão arterial sistólica - 1ª leitura
* `BPXODI1`: Pressão arterial diastólica - 1ª leitura
* `BPXOSY2`: Pressão arterial sistólica - 2ª leitura
* `BPXODI2`: Pressão arterial diastólica - 2ª leitura
* `BPXOSY3`: Pressão arterial sistólica - 3ª leitura
* `BPXODI3`: Pressão arterial diastólica - 3ª leitura
* `BPXOPLS1`: Pulso de 60 segundos - 1ª leitura
* `BPXOPLS2`: Pulso de 60 segundos - 2ª leitura
* `BPXOPLS3`: Pulso de 60 segundos - 3ª leitura

---

### bmx_df (BMX_L.xpt)
Contém dados de medidas corporais.

* `SEQN`: Número de sequência do entrevistado (Identificador)
* `BMDSTATS`: Status das Medidas Corporais
* `BMXWT`: Peso (kg)
* `BMIWT`: Comentário sobre o Peso (kg)
* `BMXRECUM`: Comprimento reclinado (cm)
* `BMIRECUM`: Comentário sobre o Comprimento Reclinado (cm)
* `BMXHEAD`: Circunferência da cabeça (cm)
* `BMIHEAD`: Comentário sobre a Circunferência da Cabeça (cm)
* `BMXHT`: Altura de pé (cm)
* `BMIHT`: Comentário sobre a Altura de Pé (cm)
* `BMXBMI`: Índice de Massa Corporal (kg/m**2)
* `BMDBMICM`: Comentário sobre o Índice de Massa Corporal (kg/m**2)
* `BMXLEG`: Comprimento da parte superior da perna (cm)
* `BMILEG`: Comentário sobre o Comprimento da Parte Superior da Perna (cm)
* `BMXARML`: Comprimento da parte superior do braço (cm)
* `BMIARML`: Comentário sobre o Comprimento da Parte Superior do Braço (cm)
* `BMXARMC`: Circunferência da parte superior do braço (cm)
* `BMIARMC`: Comentário sobre a Circunferência da Parte Superior do Braço (cm)
* `BMXWAIST`: Circunferência da cintura (cm)
* `BMIWAIST`: Comentário sobre a Circunferência da Cintura (cm)
* `BMXHIP`: Circunferência do quadril (cm)
* `BMIHIP`: Comentário sobre a Circunferência do Quadril (cm)

---

### alb_cr_df (ALB_CR_L.xpt)
Contém dados de albumina e creatinina urinária.

* `SEQN`: Número de sequência do entrevistado (Identificador)
* `URXUMA`: Albumina urinária (ug/mL)
* `URXUMS`: Albumina urinária (mg/dL)
* `URDUMALC`: Código de comentário da albumina urinária
* `URXUCR`: Creatinina urinária (mg/dL)
* `URXCRS`: Creatinina urinária (umol/L)
* `URDUCRLC`: Código de comentário da creatinina urinária
* `URDACT`: Relação albumina-creatinina urinária (mg/g)

---

### trigly_df (TRIGLY_L.xpt)
Contém dados de triglicerídeos e outros lipídios.

* `SEQN`: Número de sequência do entrevistado (Identificador)
* `WTSAF2YR`: Peso de 2 anos da subamostra em jejum
* `LBXTLG`: Triglicerídeos (mg/dL)
* `LBDTRSI`: Triglicerídeos (mmol/L)
* `LBDLDL`: Colesterol LDL (mg/dL) (cálculo de Friedewald)
* `LBDLDLSI`: Colesterol LDL (mmol/L) (cálculo de Friedewald)
* `LBDLDLM`: Colesterol LDL (mg/dL) (método direto)
* `LBDLDMSI`: Colesterol LDL (mmol/L) (método direto)
* `LBDLDLN`: Colesterol LDL (mg/dL) (método NIH)
* `LBDLDNSI`: Colesterol LDL (mmol/L) (método NIH)

---

### cbc_df (CBC_L.xpt)
Contém dados do hemograma completo.

* `SEQN`: Número de sequência do entrevistado (Identificador)
* `WTPH2YR`: Peso de 2 anos da flebotomia
* `LBXWBCSI`: Contagem de glóbulos brancos (1000 células/uL)
* `LBXLYPCT`: Percentual de linfócitos (%)
* `LBXMOPCT`: Percentual de monócitos (%)
* `LBXNEPCT`: Percentual de neutrófilos segmentados (%)
* `LBXEOPCT`: Percentual de eosinófilos (%)
* `LBXBAPCT`: Percentual de basófilos (%)
* `LBDLYMNO`: Número de linfócitos (1000 células/uL)
* `LBDMONO`: Número de monócitos (1000 células/uL)
* `LBDNEUT`: Número de neutrófilos segmentados (1000 células/uL)
* `LBDEOS`: Número de eosinófilos (1000 células/uL)
* `LBDBAS`: Número de basófilos (1000 células/uL)
* `LBXRBCSI`: Contagem de glóbulos vermelhos (milhões de células/uL)
* `LBXHGB`: Hemoglobina (g/dL)
* `LBXHCT`: Hematócrito (%)
* `LBXMCVSI`: Volume celular médio (fL)
* `LBXMC`: Hemoglobina celular média (pg)
* `LBXMCHSI`: Concentração de hemoglobina celular média (g/dL)
* `LBXRDW`: Amplitude de distribuição dos glóbulos vermelhos (%)
* `LBXPLTSI`: Contagem de plaquetas (1000 células/uL)
* `LBXMPSI`: Volume plaquetário médio (fL)
* `LBXNRBC`: Glóbulos vermelhos nucleados (100 glóbulos brancos)

---

### hdl_df (HDL_L.xpt)
Contém dados de colesterol HDL.

* `SEQN`: Número de sequência do entrevistado (Identificador)
* `WTPH2YR`: Peso de 2 anos da flebotomia
* `LBDHDD`: Colesterol HDL (mg/dL)
* `LBDHDDSI`: Colesterol HDL (mmol/L)

---

### biopro_df (BIOPRO_L.xpt)
Contém dados do perfil bioquímico.

* `SEQN`: Número de sequência do entrevistado (Identificador)
* `LBXSATSI`: Alanina aminotransferase (ALT) (U/L)
* `LBDSATLC`: Código de comentário da alanina aminotransferase (ALT)
* `LBXSAL`: Albumina (g/dL)
* `LBDSALSI`: Albumina (g/L)
* `LBXSAPSI`: Fosfatase alcalina (ALP) (U/L)
* `LBXSASSI`: Aspartato aminotransferase (AST) (U/L)
* `LBXSC3SI`: Dióxido de carbono (mmol/L)
* `LBXSBU`: Nitrogênio ureico no sangue (mg/dL)
* `LBDSBUSI`: Nitrogênio ureico no sangue (mmol/L)
* `LBXSCL`: Cloreto (mmol/L)
* `LBDSCR`: Creatinina (mg/dL)
* `LBDSCRSI`: Creatinina (umol/L)
* `LBXSGL`: Glicose (mg/dL)
    * **Nota:** Esta é a glicose sérica (aleatória). É diferente de `LBXGLU` (do arquivo `GLU_L.xpt`), que é a glicose em jejum.
* `LBXSLDSI`: Lactato desidrogenase (LDH) (U/L)
* `LBXSLTSI`: Lipase (U/L)
* `LBXSPH`: Fósforo (mg/dL)
* `LBDSPHSI`: Fósforo (mmol/L)
* `LBXSK`: Potássio (mmol/L)
* `LBXSNASI`: Sódio (mmol/L)
* `LBXSTB`: Bilirrubina total (mg/dL)
* `LBDSTBSI`: Bilirrubina total (umol/L)
* `LBXSTP`: Proteína total (g/dL)
* `LBDSTPSI`: Proteína total (g/L)
* `LBXSTR`: Colesterol total (mg/dL)
* `LBDSTRSI`: Colesterol total (mmol/L)
    * **Nota:** Esta é uma medição de colesterol total. Você também listou `LBXTC` do arquivo `TCHOL_L.xpt`. Elas medem a mesma coisa e provavelmente terão valores idênticos. Você pode manter apenas uma (ex: `LBXTC`) ao fazer o merge.
* `LBXSUA`: Ácido úrico (mg/dL)
* `LBDSUASI`: Ácido úrico (umol/L)
* `LBXSCH`: Colesterol total (mg/dL)
    * **Nota:** Outra variável de colesterol total, idêntica a `LBXSTR`.
* `LBDSCHSI`: Colesterol total (mmol/L)
* `LBXSCKSI`: Creatina quinase (CK) (U/L)
* `LBXSGTSI`: Gama glutamil transaminase (GGT) (U/L)
* `LBXSIR`: Ferro (ug/dL)
* `LBDSIRSI`: Ferro (umol/L)
* `LBXSTF`: Capacidade total de ligação do ferro (TIBC) (ug/dL)
* `LBDSTFSI`: Capacidade total de ligação do ferro (TIBC) (umol/L)
* `LBXSFG`: Ferritina (ng/mL)
* `LBXSFGSI`: Ferritina (pmol/L)
* `LBXSCA`: Cálcio (mg/dL)
* `LBDSCASI`: Cálcio (mmol/L)

---

### ins_df (INS_L.xpt)
Contém dados de insulina.

* `SEQN`: Número de sequência do entrevistado (Identificador)
* `WTSAF2YR`: Peso de 2 anos da subamostra em jejum
* `LBXIN`: Insulina (uIU/mL)
* `LBDINSI`: Insulina (pmol/L)
* `LBDINLC`: Código de comentário da insulina

---

### hscrp_df (HSCRP_L.xpt)
Contém dados da proteína C-reativa de alta sensibilidade.

* `SEQN`: Número de sequência do entrevistado (Identificador)
* `WTPH2YR`: Peso de 2 anos da flebotomia
* `LBXHSCRP`: Proteína C-reativa de alta sensibilidade (mg/L)
* `LBDHRPLC`: Código de comentário da proteína C-reativa de alta sensibilidade

---

### ghb_df (GHB_L.xpt)
Contém dados de glicohemoglobina (HbA1c).

* `SEQN`: Número de sequência do entrevistado (Identificador)
* `WTPH2YR`: Peso de 2 anos da flebotomia
* `LBXGH`: Glicohemoglobina (%)

---

### diq_df (DIQ_L.xpt)
Contém dados do questionário de diabetes.

* `SEQN`: Número de sequência do entrevistado (Identificador)
* `DIQ010`: Já lhe disseram que tinha diabetes?
* `DID040`: Idade quando lhe disseram pela primeira vez que tinha diabetes
* `DIQ160`: Já lhe disseram que tinha pré-diabetes?
* `DIQ180`: Já lhe disseram que tinha diabetes limítrofe?
* `DIQ050`: Está tomando insulina agora?
* `DID060`: Há quanto tempo toma insulina?
* `DIQ060U`: Unidade de tempo de uso da insulina
* `DIQ070`: Toma comprimidos para diabetes para baixar o açúcar no sangue?

---

### alq_df (ALQ_L.xpt)
Contém dados do questionário sobre uso de álcool.

* `SEQN`: Número de sequência do entrevistado (Identificador)
* `ALQ111`: Tomou pelo menos 12 bebidas alcoólicas/ano?
* `ALQ121`: Com que frequência bebe álcool?
* `ALQ130`: Quantas bebidas alcoólicas/dia?
* `ALQ142`: Quantos dias nos últimos 12 meses tomou >=5/4 bebidas? (Masc/Fem)
* `ALQ270`: Quantos dias nos últimos 12 meses tomou >=8/6 bebidas? (Masc/Fem)
* `ALQ280`: Quantos dias nos últimos 12 meses tomou >=12/10 bebidas? (Masc/Fem)
* `ALQ151`: Média de bebidas alcoólicas/dia - últimos 12 meses
* `ALQ170`: Idade quando começou a beber regularmente

---

### glu_df (GLU_L.xpt)
Contém dados de glicose em jejum.

* `SEQN`: Número de sequência do entrevistado (Identificador)
* `WTSAF2YR`: Peso de 2 anos da subamostra em jejum
* `LBXGLU`: Glicose em jejum (mg/dL)
* `LBDGLUSI`: Glicose em jejum (mmol/L)
    * **Nota:** Esta é a glicose *em jejum*, que é clinicamente mais relevante para o diagnóstico de diabetes/pré-diabetes do que a `LBXSGL` (aleatória) do `biopro_df`.

---

### tchol_df (TCHOL_L.xpt)
Contém dados de colesterol total.

* `SEQN`: Número de sequência do entrevistado (Identificador)
* `WTPH2YR`: Peso de 2 anos da flebotomia
* `LBXTC`: Colesterol total (mg/dL)
* `LBDTCSI`: Colesterol total (mmol/L)
    * **Nota:** Como mencionado, este é o arquivo dedicado ao colesterol total. Recomendo usar `LBXTC` como sua variável principal de colesterol total em vez das do `biopro_df` para manter a consistência.

---

### smq_df (SMQ_L.xpt)
Contém dados do questionário de tabagismo.

* `SEQN`: Número de sequência do entrevistado (Identificador)
* `SMQ020`: Fumou pelo menos 100 cigarros na vida?
* `SMQ040`: Fuma cigarros atualmente? (Alguns dias ou todos os dias)
* `SMD641`: Há quanto tempo parou de fumar cigarros? (Valor numérico)
* `SMD650`: Unidade para `SMD641` (dias, semanas, meses, anos)
* `SMD100MN`: O cigarro usual é mentolado ou não?
* `SMQ621`: (Para jovens de 12-17) Quantos cigarros fumou na vida inteira?
* `SMD630`: (Para jovens de 12-17) Idade que fumou o primeiro cigarro inteiro?
* `SMAQUEX2`: Indicador do modo do questionário (ex: CAPI, ACASI)

---

### medical_conditions_df (MCQ_L.xpt)
Contém dados do questionário de condições médicas.

* `SEQN`: Número de sequência do entrevistado (Identificador)
* `MCQ010`: Já lhe disseram que tinha asma?
* `MCQ035`: Idade quando lhe disseram que tinha asma
* `MCQ040`: Ainda tem asma?
* `MCQ050`: Teve um ataque de asma nos últimos 12 meses?
* `AGQ030`: Idade no último ataque de asma
* `MCQ053`: Devido à asma, consultou um médico?
* `MCQ149`: Já lhe disseram que tinha um rim fraco ou falhando?
* `MCQ160A`: Já lhe disseram que tinha anemia?
* `MCQ195`: Já lhe disseram que tinha gota?
* **`MCQ160B`**: Já lhe disseram que tinha insuficiência cardíaca congestiva?
* **`MCQ160C`**: Já lhe disseram que tinha doença arterial coronariana?
* **`MCQ160D`**: Já lhe disseram que tinha angina/angina pectoris?
* **`MCQ160E`**: Já lhe disseram que tinha ataque cardíaco (infarto do miocárdio)?
* **`MCQ160F`**: Já lhe disseram que tinha um derrame (AVC)?
* `MCQ160M`: Já lhe disseram que tinha alguma outra condição cardíaca?
* `MCQ170M`: Idade quando lhe disseram pela primeira vez sobre outra condição cardíaca
* `MCQ160P`: Já lhe disseram que tinha uma condição da tireoide? (Esta é a variável geral, em vez de `MCQ220`)
* `MCQ160L`: Já lhe disseram que tinha bronquite crônica?
* `MCQ170L`: Idade quando lhe disseram pela primeira vez sobre bronquite crônica
* `MCQ500`: Já lhe disseram que tinha enfisema?
* `MCQ510A`: Já lhe disseram que tinha artrite?
* `MCQ510B`: Já lhe disseram que tinha artrite reumatoide?
* `MCQ510C`: Já lhe disseram que tinha osteoartrite?
* `MCQ510D`: Já lhe disseram que tinha outro tipo de artrite?
* `MCQ510E`: Já lhe disseram que tinha fibromialgia, bursite ou tendinite?
* `MCQ510F`: Já lhe disseram que tinha lúpus?
* `MCQ550`: Já lhe disseram que tinha ossos fracos/osteoporose?
* `MCQ560`: Já lhe disseram que tinha úlcera?

---

### physical_activity_df (PAQ_L.xpt)
Contém dados do questionário de atividades físicas. Leisure-Time Physical Activity: Atividade Física no Tempo Livre.

* `SEQN`: Número de sequência do entrevistado (Identificador)
* `PAD790Q`: Frequência de LTPA moderada
* `PAD790U`: Unidade de LTPA moderada (dia/semana/mês/ano)
* `PAD800`: Minutos de LTPA moderada
* `PAD810Q`: Frequência de LTPA intensa
* `PAD810U`: Unidade de LTPA intensa (dia/semana/mês/ano)
* `PAD820`: Minutos de LTPA intensa
* `PAD680`: Minutos de atividade sedentária

## Importação de Bibliotecas

In [23]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import plotly.express as px

## Preparação dos datasets

In [24]:
demographic_df = pd.read_sas('DEMO_L.xpt')
demographic_df.head()

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDAGEMN,RIDRETH1,RIDRETH3,RIDEXMON,RIDEXAGM,...,DMDHRGND,DMDHRAGZ,DMDHREDZ,DMDHRMAZ,DMDHSEDZ,WTINT2YR,WTMEC2YR,SDMVSTRA,SDMVPSU,INDFMPIR
0,130378.0,12.0,2.0,1.0,43.0,NaN,5.0,6.0,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,50055.450807,54374.463898,173.0,2.0,5.00
1,130379.0,12.0,2.0,1.0,66.0,NaN,3.0,3.0,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,29087.450605,34084.721548,173.0,2.0,5.00
2,130380.0,12.0,2.0,2.0,44.0,NaN,2.0,2.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,80062.674301,81196.277992,174.0,1.0,1.41
3,130381.0,12.0,2.0,2.0,5.0,NaN,5.0,7.0,1.0,71.0,...,2.0,2.0,2.0,3.0,NaN,38807.268902,55698.607106,182.0,2.0,1.53
4,130382.0,12.0,2.0,1.0,2.0,NaN,3.0,3.0,2.0,34.0,...,2.0,2.0,3.0,1.0,2.0,30607.519774,36434.146346,182.0,2.0,3.60

In [25]:
bpxo_df = pd.read_sas('BPXO_L.xpt')
display(bpxo_df.head())

,SEQN,BPAOARM,BPAOCSZ,BPXOSY1,BPXODI1,BPXOSY2,BPXODI2,BPXOSY3,BPXODI3,BPXOPLS1,BPXOPLS2,BPXOPLS3
0,130378.0,b'R',4.0,135.0,98.0,131.0,96.0,132.0,94.0,82.0,79.0,82.0
1,130379.0,b'R',4.0,121.0,84.0,117.0,76.0,113.0,76.0,72.0,71.0,73.0
2,130380.0,b'R',4.0,111.0,79.0,112.0,80.0,104.0,76.0,84.0,83.0,77.0
3,130386.0,b'R',4.0,110.0,72.0,120.0,74.0,115.0,75.0,59.0,64.0,64.0
4,130387.0,b'R',4.0,143.0,76.0,136.0,74.0,145.0,78.0,80.0,80.0,77.0

In [26]:
bmx_df = pd.read_sas('BMX_L.xpt')
display(bmx_df.head())

,SEQN,BMDSTATS,BMXWT,BMIWT,BMXRECUM,BMIRECUM,BMXHEAD,BMIHEAD,BMXHT,BMIHT,...,BMXLEG,BMILEG,BMXARML,BMIARML,BMXARMC,BMIARMC,BMXWAIST,BMIWAIST,BMXHIP,BMIHIP
0,130378.0,1.0,86.9,NaN,NaN,NaN,NaN,NaN,179.5,NaN,...,42.8,NaN,42.0,NaN,35.7,NaN,98.3,NaN,102.9,NaN
1,130379.0,1.0,101.8,NaN,NaN,NaN,NaN,NaN,174.2,NaN,...,38.5,NaN,38.7,NaN,33.7,NaN,114.7,NaN,112.4,NaN
2,130380.0,1.0,69.4,NaN,NaN,NaN,NaN,NaN,152.9,NaN,...,38.5,NaN,35.5,NaN,36.3,NaN,93.5,NaN,98.0,NaN
3,130381.0,1.0,34.3,NaN,NaN,NaN,NaN,NaN,120.1,NaN,...,NaN,NaN,25.4,NaN,23.4,NaN,70.4,NaN,NaN,NaN
4,130382.0,3.0,13.6,NaN,NaN,1.0,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,1.0,NaN,1.0,NaN,1.0,NaN,NaN

In [27]:
alb_cr_df = pd.read_sas('ALB_CR_L.xpt')
display(alb_cr_df.head())

,SEQN,URXUMA,URXUMS,URDUMALC,URXUCR,URXCRS,URDUCRLC,URDACT
0,130378.0,23.12,23.12,5.397605e-79,136.0,12022.4,5.397605e-79,17.00
1,130379.0,4.25,4.25,5.397605e-79,64.0,5657.6,5.397605e-79,6.64
2,130380.0,12.43,12.43,5.397605e-79,157.0,13878.8,5.397605e-79,7.92
3,130381.0,16.12,16.12,5.397605e-79,208.0,18387.2,5.397605e-79,7.75
4,130386.0,4.60,4.60,5.397605e-79,113.0,9989.2,5.397605e-79,4.07

In [28]:
trigly_df = pd.read_sas('TRIGLY_L.xpt')
display(trigly_df.head())

,SEQN,WTSAF2YR,LBXTLG,LBDTRSI,LBDLDL,LBDLDLSI,LBDLDLM,LBDLDMSI,LBDLDLN,LBDLDNSI
0,130378.0,1.200253e+05,153.0,1.727,188.0,4.862,190.0,4.913,191.0,4.939
1,130379.0,5.397605e-79,86.0,0.971,137.0,3.543,135.0,3.491,139.0,3.595
2,130380.0,1.450908e+05,375.0,4.234,63.0,1.629,90.0,2.327,78.0,2.017
3,130386.0,8.259962e+04,142.0,1.603,109.0,2.819,111.0,2.870,112.0,2.896
4,130394.0,1.004203e+05,57.0,0.644,124.0,3.207,120.0,3.103,124.0,3.207

In [29]:
cbc_df = pd.read_sas('CBC_L.xpt')
display(cbc_df.head())

,SEQN,WTPH2YR,LBXWBCSI,LBXLYPCT,LBXMOPCT,LBXNEPCT,LBXEOPCT,LBXBAPCT,LBDLYMNO,LBDMONO,...,LBXRBCSI,LBXHGB,LBXHCT,LBXMCVSI,LBXMC,LBXMCHSI,LBXRDW,LBXPLTSI,LBXMPSI,LBXNRBC
0,130378.0,5.604213e+04,4.7,40.8,6.8,46.1,5.2,1.2,1.9,0.3,...,5.19,15.7,45.3,87.4,34.6,30.2,12.9,259.0,7.8,0.3
1,130379.0,3.743571e+04,6.3,25.4,14.2,57.3,2.5,0.7,1.6,0.9,...,4.59,15.2,43.9,95.8,34.5,33.0,12.8,221.0,8.5,0.1
2,130380.0,8.532884e+04,5.7,29.9,5.5,58.5,5.3,0.9,1.7,0.3,...,4.86,13.8,40.1,82.5,34.4,28.3,13.3,235.0,9.1,0.1
3,130381.0,5.397605e-79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,130382.0,5.963893e+04,11.4,29.9,8.3,60.1,1.2,0.6,3.4,0.9,...,4.61,12.3,36.5,79.2,33.6,26.7,14.6,342.0,7.4,0.1

In [30]:
hdl_df = pd.read_sas('HDL_L.xpt')
display(hdl_df.head())

       SEQN       WTPH2YR  LBDHDD  LBDHDDSI
0  130378.0  56042.129410    45.0      1.16
1  130379.0  37435.705647    60.0      1.55
2  130380.0  85328.844519    49.0      1.27
3  130386.0  44526.214135    46.0      1.19
4  130387.0  22746.296353    42.0      1.09

In [31]:
biopro_df = pd.read_sas('BIOPRO_L.xpt')
display(biopro_df.head())

,SEQN,LBXSATSI,LBDSATLC,LBXSAL,LBDSALSI,LBXSAPSI,LBXSASSI,LBXSC3SI,LBXSBU,LBDSBUSI,...,LBXSCA,LBDSCASI,LBXSCH,LBDSCHSI,LBXSTP,LBDSTPSI,LBXSTR,LBDSTRSI,LBXSUA,LBDSUASI
0,130378.0,39.0,5.397605e-79,4.3,43.0,91.0,25.0,24.0,11.0,3.9,...,9.6,2.4,266.0,6.89,7.5,75.0,153.0,1.73,5.1,303.3
1,130379.0,17.0,5.397605e-79,3.9,39.0,64.0,20.0,25.0,24.0,8.6,...,9.4,2.4,217.0,5.62,7.3,73.0,88.0,0.99,8.5,505.6
2,130380.0,13.0,5.397605e-79,3.7,37.0,78.0,15.0,25.0,10.0,3.6,...,9.4,2.4,183.0,4.74,7.6,76.0,375.0,4.24,4.4,261.7
3,130386.0,34.0,5.397605e-79,4.3,43.0,54.0,20.0,21.0,17.0,6.1,...,9.5,2.4,185.0,4.79,6.9,69.0,140.0,1.58,6.0,356.9
4,130387.0,12.0,5.397605e-79,3.7,37.0,116.0,13.0,24.0,15.0,5.4,...,9.3,2.3,203.0,5.26,6.7,67.0,111.0,1.25,6.2,368.8

In [32]:
ins_df = pd.read_sas('INS_L.xpt')
display(ins_df.head())

       SEQN      WTSAF2YR  LBXIN  LBDINSI       LBDINLC
0  130378.0  1.200253e+05  15.53    93.18  5.397605e-79
1  130379.0  5.397605e-79  19.91   119.46  5.397605e-79
2  130380.0  1.450908e+05  16.33    97.98  5.397605e-79
3  130386.0  8.259962e+04  11.38    68.28  5.397605e-79
4  130394.0  1.004203e+05   7.20    43.20  5.397605e-79

In [33]:
hscrp_df = pd.read_sas('HSCRP_L.xpt')
display(hscrp_df.head())

       SEQN       WTPH2YR  LBXHSCRP      LBDHRPLC
0  130378.0  5.604213e+04      1.78  5.397605e-79
1  130379.0  3.743571e+04      2.03  5.397605e-79
2  130380.0  8.532884e+04      5.62  5.397605e-79
3  130381.0  5.397605e-79       NaN           NaN
4  130382.0  5.963893e+04       NaN           NaN

In [34]:
ghb_df = pd.read_sas('GHB_L.xpt')
display(ghb_df.head())

       SEQN       WTPH2YR  LBXGH
0  130378.0  56042.129410    5.6
1  130379.0  37435.705647    5.6
2  130380.0  85328.844519    6.2
3  130386.0  44526.214135    5.1
4  130387.0  22746.296353    5.9

In [35]:
diq_df = pd.read_sas('DIQ_L.xpt')
display(diq_df.head())

       SEQN  DIQ010  DID040  DIQ160  DIQ180  DIQ050  DID060  DIQ060U  DIQ070
0  130378.0     2.0     NaN     2.0     2.0     NaN     NaN      NaN     NaN
1  130379.0     2.0     NaN     2.0     1.0     NaN     NaN      NaN     NaN
2  130380.0     1.0    35.0     NaN     NaN     2.0     NaN      NaN     1.0
3  130381.0     2.0     NaN     NaN     NaN     NaN     NaN      NaN     NaN
4  130382.0     2.0     NaN     NaN     NaN     NaN     NaN      NaN     NaN

In [36]:
alq_df = pd.read_sas('ALQ_L.xpt')
display(alq_df.head())

,SEQN,ALQ111,ALQ121,ALQ130,ALQ142,ALQ270,ALQ280,ALQ151,ALQ170
0,130378.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,130379.0,1.0,2.000000e+00,3.0,5.397605e-79,NaN,NaN,2.0,NaN
2,130380.0,1.0,1.000000e+01,1.0,5.397605e-79,NaN,NaN,2.0,NaN
3,130386.0,1.0,4.000000e+00,2.0,1.000000e+01,5.397605e-79,10.0,2.0,5.397605e-79
4,130387.0,1.0,5.397605e-79,NaN,NaN,NaN,NaN,2.0,NaN

In [37]:
glu_df = pd.read_sas('GLU_L.xpt')
display(glu_df.head())

       SEQN      WTSAF2YR  LBXGLU  LBDGLUSI
0  130378.0  1.200253e+05   113.0      6.27
1  130379.0  5.397605e-79    99.0      5.50
2  130380.0  1.450908e+05   156.0      8.66
3  130386.0  8.259962e+04   100.0      5.55
4  130394.0  1.004203e+05    88.0      4.88

In [38]:
tchol_df = pd.read_sas('TCHOL_L.xpt')
display(tchol_df.head())

       SEQN       WTPH2YR  LBXTC  LBDTCSI
0  130378.0  56042.129410  264.0     6.83
1  130379.0  37435.705647  214.0     5.53
2  130380.0  85328.844519  187.0     4.84
3  130386.0  44526.214135  183.0     4.73
4  130387.0  22746.296353  203.0     5.25

In [39]:
smq_df = pd.read_sas('SMQ_L.xpt')
display(smq_df.head())

,SEQN,SMQ020,SMQ040,SMD641,SMD650,SMD100MN,SMQ621,SMD630,SMAQUEX2
0,130378.0,1.0,3.0,NaN,NaN,NaN,NaN,NaN,1.0
1,130379.0,1.0,3.0,NaN,NaN,NaN,NaN,NaN,1.0
2,130380.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0
3,130384.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0
4,130385.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0

In [40]:
medical_conditions_df = pd.read_sas('MCQ_L.xpt')
display(medical_conditions_df.head())

,SEQN,MCQ010,MCQ035,MCQ040,MCQ050,AGQ030,MCQ053,MCQ149,MCQ160A,MCQ195,...,MCQ510E,MCQ510F,MCQ550,MCQ560,MCQ220,MCQ230A,MCQ230B,MCQ230C,MCQ230D,OSQ230
0,130378.0,2.0,NaN,NaN,NaN,2.0,2.0,NaN,1.0,2.0,...,NaN,NaN,2.0,2.0,2.0,NaN,NaN,NaN,NaN,2.0
1,130379.0,2.0,NaN,NaN,NaN,2.0,2.0,NaN,2.0,NaN,...,NaN,NaN,2.0,2.0,1.0,30.0,NaN,NaN,NaN,1.0
2,130380.0,2.0,NaN,NaN,NaN,2.0,2.0,NaN,2.0,NaN,...,NaN,NaN,2.0,2.0,2.0,NaN,NaN,NaN,NaN,1.0
3,130381.0,2.0,NaN,NaN,NaN,1.0,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,130382.0,2.0,NaN,NaN,NaN,2.0,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
physical_activity_df = pd.read_sas('PAQ_L.xpt')
display(physical_activity_df.head())

,SEQN,PAD790Q,PAD790U,PAD800,PAD810Q,PAD810U,PAD820,PAD680
0,130378.0,3.000000e+00,b'W',45.0,3.000000e+00,b'W',45.0,360.0
1,130379.0,4.000000e+00,b'W',45.0,3.000000e+00,b'W',45.0,480.0
2,130380.0,1.000000e+00,b'W',20.0,5.397605e-79,b'',NaN,240.0
3,130384.0,5.397605e-79,b'',NaN,5.397605e-79,b'',NaN,60.0
4,130385.0,1.000000e+00,b'D',90.0,1.000000e+00,b'W',60.0,180.0

In [42]:
# The demographic dataset is the base
merged_df = demographic_df.copy()

# Datasets to merge with demographic one
other_dfs = [
    bpxo_df, bmx_df, alb_cr_df, trigly_df, cbc_df, hdl_df,
    biopro_df, ins_df, hscrp_df, ghb_df, diq_df, alq_df,
    glu_df, tchol_df, smq_df, medical_conditions_df, physical_activity_df
]

# Merging datasets
for df_to_merge in other_dfs:

    # Only select the SEQN (identifier of person) and the columns not present in 'merged_df'
    cols_to_keep = ['SEQN']
    new_cols = [col for col in df_to_merge.columns if col not in merged_df.columns]
    cols_to_keep.extend(new_cols)

    merged_df = merged_df.merge(
        df_to_merge[cols_to_keep],
        on='SEQN',
        how='outer'
    )

display(merged_df.head())
merged_df.info()

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDAGEMN,RIDRETH1,RIDRETH3,RIDEXMON,RIDEXAGM,...,MCQ230C,MCQ230D,OSQ230,PAD790Q,PAD790U,PAD800,PAD810Q,PAD810U,PAD820,PAD680
0,130378.0,12.0,2.0,1.0,43.0,NaN,5.0,6.0,2.0,NaN,...,NaN,NaN,2.0,3.0,b'W',45.0,3.000000e+00,b'W',45.0,360.0
1,130379.0,12.0,2.0,1.0,66.0,NaN,3.0,3.0,2.0,NaN,...,NaN,NaN,1.0,4.0,b'W',45.0,3.000000e+00,b'W',45.0,480.0
2,130380.0,12.0,2.0,2.0,44.0,NaN,2.0,2.0,1.0,NaN,...,NaN,NaN,1.0,1.0,b'W',20.0,5.397605e-79,b'',NaN,240.0
3,130381.0,12.0,2.0,2.0,5.0,NaN,5.0,7.0,1.0,71.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,130382.0,12.0,2.0,1.0,2.0,NaN,3.0,3.0,2.0,34.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11933 entries, 0 to 11932
Columns: 215 entries, SEQN to PAD680
dtypes: float64(212), object(3)
memory usage: 19.6+ MB

The fields in Medical Condtions Dataframe related to CVDs are:
* MCQ160b - Ever told had congestive heart failure
* MCQ160c - Ever told you had coronary heart disease
* MCQ160d - Ever told you had angina/angina pectoris
* MCQ160e - Ever told you had heart attack
* MCQ160f - Ever told you had a stroke

In [43]:
# Remove rows with NaN values in the specified columns
merged_df.dropna(subset=['MCQ160B', 'MCQ160C', 'MCQ160D', 'MCQ160E', 'MCQ160F'], inplace=True)

# Create the 'target' column
# A value of 1.0 for these columns indicates a positive response
merged_df['target'] = ((merged_df['MCQ160B'] == 1.0) |
                    (merged_df['MCQ160C'] == 1.0) |
                    (merged_df['MCQ160D'] == 1.0) |
                    (merged_df['MCQ160E'] == 1.0) |
                    (merged_df['MCQ160F'] == 1.0)).astype(int)

# Display the first few rows with the new 'target' column
display(merged_df.info())
display(merged_df.head())

merged_df['target'].value_counts()

<class 'pandas.core.frame.DataFrame'>
Index: 7806 entries, 0 to 11932
Columns: 216 entries, SEQN to target
dtypes: float64(212), int64(1), object(3)
memory usage: 12.9+ MB

None

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDAGEMN,RIDRETH1,RIDRETH3,RIDEXMON,RIDEXAGM,...,MCQ230D,OSQ230,PAD790Q,PAD790U,PAD800,PAD810Q,PAD810U,PAD820,PAD680,target
0,130378.0,12.0,2.0,1.0,43.0,NaN,5.0,6.0,2.0,NaN,...,NaN,2.0,3.000000e+00,b'W',45.0,3.000000e+00,b'W',45.0,360.0,0
1,130379.0,12.0,2.0,1.0,66.0,NaN,3.0,3.0,2.0,NaN,...,NaN,1.0,4.000000e+00,b'W',45.0,3.000000e+00,b'W',45.0,480.0,0
2,130380.0,12.0,2.0,2.0,44.0,NaN,2.0,2.0,1.0,NaN,...,NaN,1.0,1.000000e+00,b'W',20.0,5.397605e-79,b'',NaN,240.0,0
6,130384.0,12.0,1.0,1.0,43.0,NaN,1.0,1.0,NaN,NaN,...,NaN,2.0,5.397605e-79,b'',NaN,5.397605e-79,b'',NaN,60.0,0
7,130385.0,12.0,1.0,2.0,65.0,NaN,3.0,3.0,NaN,NaN,...,NaN,2.0,1.000000e+00,b'D',90.0,1.000000e+00,b'W',60.0,180.0,0

target
0    6824
1     982
Name: count, dtype: int64

In [44]:
# Save the merged dataframe to a CSV file
# index=False prevents saving the pandas index (row number column) to the file
merged_df.to_csv('nhanes_2021_2023_merged_data.csv', index=False)